---
# sshd_config/tasks/main.yml

- name: "Load variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"

# code from https://www.samdarwin.com/ansible-default-vars/
#   ansible converts 'yes'/'no' to Booleans with set_fact.
#   This cannot be prevented, so the template later converts
#   Booleans back to 'yes'/'no' for those parameters that
#   need them.
#   https://github.com/ansible/ansible/issues/11905
- name: 'set facts based on defaults'
  ansible.builtin.set_fact:
    "{{ item[8:] }}": "{{ lookup('vars', item) }}"
  loop: "{{ vars | list }}"
  when:
    - item is match("^default_")
    - vars[item[8:]] is undefined

- name: 'Modify the sshd_config file'
  ansible.builtin.template:
    src: 'sshd_config.j2'
    dest: "{{ path_to_sshd_config }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart the sshd service'
